version: '3.3'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        image: flashcard
        container_name: flashcard
        restart: unless-stopped
        env_file: .env
        # environment:
            # USER: caffeines
        ports:
            - 4000:4000
        volumes:
            - .:/home/flashcard/app
             - /home/flashcard/app/node_modules
        networks:
            - app-network
        # command: npx pm2 start ecosystem.config.js --no-daemon
        command: node app.js
networks:
  app-network:
    driver: bridge